version: "3.9"

networks:
  pagemyself:
    driver: bridge

services:
  web:
    image: 'bitnami/nginx:1.21'
    restart: on-failure
    depends_on:
      - phpfpm
      - db
    networks:
      - pagemyself
    ports:
      - "${WEBPORT}:80"
    volumes:
      - ./app:/pagemyself
      - ./nginx-config.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf
  phpfpm:
    build: .
    restart: on-failure
    networks:
      - pagemyself
    volumes:
      - ./app:/pagemyself
      - ./php-fpm.conf:/opt/bitnami/php/etc/php-fpm.d/www-custom.conf
    environment:
      - FRAMELIX_SETUP_DB_HOST=db
      - FRAMELIX_SETUP_DB_USER=pagemyself
      - FRAMELIX_SETUP_DB_PASS=pagemyself
      - FRAMELIX_SETUP_DB_NAME=pagemyself
  db:
    image: mariadb:10.7
    restart: on-failure
    networks:
      - pagemyself
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: 1
      MARIADB_USER: pagemyself
      MARIADB_PASSWORD : pagemyself
      MARIADB_DATABASE : pagemyself