version: "3.9"

networks:
  app:
    driver: bridge

services:
  web:
    image: 'bitnami/nginx:latest'
    depends_on:
      - phpfpm
    networks:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./nginx-config.conf:/opt/bitnami/nginx/conf/server_blocks/default.conf
  phpfpm:
    image: 'bitnami/php-fpm:8.1-prod'
    networks:
      - app
    volumes:
      - ./app:/app